### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by ainsleyclark** [steeve/ryzentosh#2]
Hi @steeve 

This EFI worked like a charm, thanks for putting it up.
Will you be making regular updates for later releases of Mac as well as opencore? 

Many thanks.

**Comment by steeve** [comment]
I will, probably not for every OpenCore release, but when I update my own machine, I'll update this repo.

**Comment by steeve** [comment]
Also, glad it worked for you !

**Comment by ainsleyclark** [comment]
Thanks @steeve 👌
