### ISSUE TITLE
Realtek 2.5G Lan

### ISSUE THREAD

**Issue by ainsleyclark** [steeve/ryzentosh#3]
Hi @steeve 

Did you manage to get the 2.5g Realtek Ethernet working? Works fine on the 1g Intel but just displays as not connected when I try to connect.

Many thanks.

**Comment by steeve** [comment]
Yeah, you need to set the duplex speed manually (found this info on a forum, and it worked):
![image](https://user-images.githubusercontent.com/137467/112725791-3ec5bc80-8f1a-11eb-81c8-e7418feea292.png)

**Comment by ainsleyclark** [comment]
Ah thank you so much!

Worked like a charm, thanks for the continued support!
