### ISSUE TITLE
Updating to 11.3.1

### ISSUE THREAD

**Issue by ainsleyclark** [steeve/ryzentosh#4]
Hi @steeve 

Just a quick question. I currently have 11.2.3 installed. When I try to update to 11.3.1 it downloads and restarts and usually I see a `MacOS Installer` from OpenCanopy but it doesn't show up. I have to boot into macOS again and it just tells me there is an update to do!
Is there something I'm missing?

Many thanks again.

**Comment by ainsleyclark** [comment]
Sorry it comes up as `Macintosh HD`, goes in then just hangs.

**Comment by ainsleyclark** [comment]
Getting stuck here:
![IMG_5523](https://user-images.githubusercontent.com/34712954/118175091-8e5b3b80-b427-11eb-87b2-94639a6d594e.jpeg)

**Comment by steeve** [comment]
Ah right, you need to update the patches in the plist from https://github.com/AMD-OSX/AMD_Vanilla

I forgot to upload them here.

**Comment by ainsleyclark** [comment]
Thanks @steeve appreciate you getting back to me.

Do you know how to merge the plist? Presuming it's 16h we need?

Many thanks again.

**Comment by ainsleyclark** [comment]
Got it working thank you @steeve 
Would you like me to make a pull request to update the patches?
Many thanks.
