### ISSUE TITLE
Monterey

### ISSUE THREAD

**Issue by ainsleyclark** [steeve/ryzentosh#7]
Hey @steeve have you tested Monterey with the current OC version? Have identical system to you.

Thanks!

**Comment by ainsleyclark** [comment]
Hey @steeve would it be possible for a bump to OC 0.7.4? I tried but failed miserably!

**Comment by steeve** [comment]
I have not tried Monterey yet! Nor OC 0.7.4! I'll round to it when I get some time

**Comment by ainsleyclark** [comment]
Thank you @steeve !

**Comment by ainsleyclark** [comment]
Hey @steeve just wondering if you had the time to look at updating OC?

Thank you!
